#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  button1,        sensorTouch)
#pragma config(Sensor, dgtl2,  button2,        sensorTouch)
#pragma config(Sensor, dgtl3,  button3,        sensorTouch)
#pragma config(Sensor, dgtl4,  button4,        sensorTouch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port2,           motor2,        tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          motor3,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true){
	if(SensorValue(button1) == 1){

	resetMotorEncoder(port2);

	resetMotorEncoder(port1);


		while(getMotorEncoder(port1) < 1670){

			motor[port1] = 80;

			motor[port2] = -60;
		}
		motor[port1] = 0;
		motor[port2] = 0;
	}
	if(SensorValue(button2) == 1){
		resetMotorEncoder(port2);

	resetMotorEncoder(port1);

		while(getMotorEncoder(port1) > -425)
			{
			motor[port1] = -50;
			motor[port2] = -50;
		}
		motor[port1] = 0;
		motor[port2] = 0;
}
if(SensorValue(button3) == 1){
	while(SensorValue(button4) == 0){
		motor[port3] = -25;
	}
motor[port3] = 0;

if (SensorValue(button4) == 1){
	motor[port3] = 25;
	wait1Msec(2000);
	motor[port3] = 0;
	wait1Msec(500);
	motor[port1] = -25;
	motor[port2] = 25;
	wait1Msec(2000);
	motor[port1] = 0;
	motor[port2] = 0;
}
}
}
}
